// <auto-generated />
using System;
using AiNexus.BuildingBlocks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiNexus.BuildingBlocks.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20261003175044_AccessControl")]
    partial class AccessControl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiNexus.Modules.AccessControl.Feature", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Features", "access");

                    b.HasData(
                        new
                        {
                            Id = "chat",
                            Enabled = true,
                            Name = "AI 對話",
                            Route = "/chat",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "access");

                    b.HasData(
                        new
                        {
                            Id = "member",
                            Enabled = true,
                            Name = "一般使用者"
                        });
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.RoleGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("RoleGroups", "access");

                    b.HasData(
                        new
                        {
                            Id = "workspace",
                            Enabled = true,
                            Name = "基本工作台"
                        });
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.RoleGroupFeature", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FeatureId")
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("GroupId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("RoleGroupFeatures", "access");

                    b.HasData(
                        new
                        {
                            GroupId = "workspace",
                            FeatureId = "chat"
                        });
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.RoleGroupRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("RoleId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("RoleGroupRoles", "access");

                    b.HasData(
                        new
                        {
                            RoleId = "member",
                            GroupId = "workspace"
                        });
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "access");
                });

            modelBuilder.Entity("AiNexus.Modules.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveLeafId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "IsDeleted", "UpdatedAt");

                    b.ToTable("Conversations", "conversations");
                });

            modelBuilder.Entity("AiNexus.Modules.Conversations.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModelId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("Messages", "conversations");
                });

            modelBuilder.Entity("AiNexus.Modules.Identity.NexusUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Sid")
                        .IsRequired()
                        .HasMaxLength(184)
                        .HasColumnType("nvarchar(184)");

                    b.HasKey("Id");

                    b.HasIndex("Sid")
                        .IsUnique();

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("AiNexus.Modules.Inference.GenerationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssistantMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActiveOwnerId")
                        .IsUnique()
                        .HasFilter("[ActiveOwnerId] IS NOT NULL");

                    b.HasIndex("AssistantMessageId");

                    b.HasIndex("UserMessageId");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.HasIndex("OwnerId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("GenerationRuns", "inference");
                });

            modelBuilder.Entity("AiNexus.Modules.Inference.ModelProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("ContextTokens")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("int");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsUsage")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ModelProfiles", "inference");
                });

            modelBuilder.Entity("AiNexus.Modules.Inference.RunEvent", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Delta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("RunId", "Sequence");

                    b.ToTable("RunEvents", "inference");
                });

            modelBuilder.Entity("AiNexus.Modules.Operations.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Result")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("AuditEvents", "operations");
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.RoleGroupFeature", b =>
                {
                    b.HasOne("AiNexus.Modules.AccessControl.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.AccessControl.RoleGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.RoleGroupRole", b =>
                {
                    b.HasOne("AiNexus.Modules.AccessControl.RoleGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.AccessControl.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.UserRole", b =>
                {
                    b.HasOne("AiNexus.Modules.AccessControl.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Identity.NexusUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Conversations.Conversation", b =>
                {
                    b.HasOne("AiNexus.Modules.Identity.NexusUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Conversations.Message", b =>
                {
                    b.HasOne("AiNexus.Modules.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Conversations.Message", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AiNexus.Modules.Identity.NexusUser", b =>
                {
                    b.OwnsOne("AiNexus.Modules.Identity.UserPreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("NexusUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DefaultModelId")
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)");

                            b1.Property<bool>("ReducedMotion")
                                .HasColumnType("bit");

                            b1.Property<string>("Theme")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)");

                            b1.HasKey("NexusUserId");

                            b1.ToTable("UserPreferences", "identity");

                            b1.WithOwner()
                                .HasForeignKey("NexusUserId");
                        });

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Inference.GenerationRun", b =>
                {
                    b.HasOne("AiNexus.Modules.Conversations.Message", null)
                        .WithMany()
                        .HasForeignKey("AssistantMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Identity.NexusUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Conversations.Message", null)
                        .WithMany()
                        .HasForeignKey("UserMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Inference.RunEvent", b =>
                {
                    b.HasOne("AiNexus.Modules.Inference.GenerationRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
