// <auto-generated />
using System;
using AiNexus.BuildingBlocks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiNexus.BuildingBlocks.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20261004062441_Projects")]
    partial class Projects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiNexus.Modules.AccessControl.Feature", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Features", "access");

                    b.HasData(
                        new
                        {
                            Id = "chat",
                            Enabled = true,
                            Name = "AI 對話",
                            Route = "/chat",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = "admin",
                            Enabled = true,
                            Name = "管理",
                            Route = "/admin",
                            SortOrder = 90
                        },
                        new
                        {
                            Id = "projects",
                            Enabled = true,
                            Name = "專案",
                            Route = "/projects",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = "knowledge",
                            Enabled = true,
                            Name = "知識庫",
                            Route = "/knowledge",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = "tasks",
                            Enabled = true,
                            Name = "背景任務",
                            Route = "/tasks",
                            SortOrder = 70
                        },
                        new
                        {
                            Id = "artifacts",
                            Enabled = true,
                            Name = "成果文件",
                            Route = "/artifacts",
                            SortOrder = 40
                        });
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "access");

                    b.HasData(
                        new
                        {
                            Id = "member",
                            Enabled = true,
                            Name = "一般使用者"
                        },
                        new
                        {
                            Id = "administrator",
                            Enabled = true,
                            Name = "平台管理員"
                        });
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.RoleGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("RoleGroups", "access");

                    b.HasData(
                        new
                        {
                            Id = "workspace",
                            Enabled = true,
                            Name = "基本工作\u53f0"
                        },
                        new
                        {
                            Id = "administrators",
                            Enabled = true,
                            Name = "平台管理"
                        });
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.RoleGroupFeature", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FeatureId")
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("GroupId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("RoleGroupFeatures", "access");

                    b.HasData(
                        new
                        {
                            GroupId = "workspace",
                            FeatureId = "chat"
                        },
                        new
                        {
                            GroupId = "administrators",
                            FeatureId = "admin"
                        },
                        new
                        {
                            GroupId = "workspace",
                            FeatureId = "projects"
                        },
                        new
                        {
                            GroupId = "workspace",
                            FeatureId = "knowledge"
                        },
                        new
                        {
                            GroupId = "workspace",
                            FeatureId = "tasks"
                        },
                        new
                        {
                            GroupId = "workspace",
                            FeatureId = "artifacts"
                        });
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.RoleGroupRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("RoleId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("RoleGroupRoles", "access");

                    b.HasData(
                        new
                        {
                            RoleId = "member",
                            GroupId = "workspace"
                        },
                        new
                        {
                            RoleId = "administrator",
                            GroupId = "administrators"
                        });
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "access");
                });

            modelBuilder.Entity("AiNexus.Modules.Administration.AdministratorBootstrap", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId");

                    b.ToTable("AdministratorBootstraps", "access");
                });

            modelBuilder.Entity("AiNexus.Modules.Administration.GroupModelPolicy", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AllowedModelsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("DailyRequestLimit")
                        .HasColumnType("int");

                    b.Property<long?>("StoredAttachmentLimitBytes")
                        .HasColumnType("bigint");

                    b.HasKey("GroupId");

                    b.ToTable("GroupModelPolicies", "access");
                });

            modelBuilder.Entity("AiNexus.Modules.Artifacts.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SourceMessageId");

                    b.ToTable("Artifacts", "content");
                });

            modelBuilder.Entity("AiNexus.Modules.Artifacts.ArtifactRevision", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(64000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("ArtifactId", "Version");

                    b.HasIndex("AuthorId");

                    b.ToTable("ArtifactRevisions", "content");
                });

            modelBuilder.Entity("AiNexus.Modules.Attachments.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "CreatedAt");

                    b.ToTable("Attachments", "attachments");
                });

            modelBuilder.Entity("AiNexus.Modules.Attachments.AttachmentReference", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResourceId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("ResourceAttachments", "attachments");
                });

            modelBuilder.Entity("AiNexus.Modules.Attachments.MessageAttachment", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MessageId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("MessageAttachments", "attachments");
                });

            modelBuilder.Entity("AiNexus.Modules.Collaboration.ResourceGroup", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroupId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("ResourceId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("ResourceGroups", "collaboration");
                });

            modelBuilder.Entity("AiNexus.Modules.Collaboration.ResourceMember", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("ResourceId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ResourceMembers", "collaboration");
                });

            modelBuilder.Entity("AiNexus.Modules.Collaboration.WorkspaceResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("OwnerId", "Kind", "UpdatedAt");

                    b.ToTable("Resources", "collaboration");
                });

            modelBuilder.Entity("AiNexus.Modules.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveLeafId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SystemInstruction")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("OwnerId", "IsDeleted", "UpdatedAt");

                    b.HasIndex("OwnerId", "IsDeleted", "IsArchived", "IsFavorite", "UpdatedAt");

                    b.ToTable("Conversations", "conversations");
                });

            modelBuilder.Entity("AiNexus.Modules.Conversations.ConversationLabel", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("ConversationId", "Name");

                    b.ToTable("ConversationLabels", "conversations");
                });

            modelBuilder.Entity("AiNexus.Modules.Conversations.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ModelId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("Messages", "conversations");
                });

            modelBuilder.Entity("AiNexus.Modules.Identity.NexusUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Sid")
                        .IsRequired()
                        .HasMaxLength(184)
                        .HasColumnType("nvarchar(184)");

                    b.HasKey("Id");

                    b.HasIndex("Sid")
                        .IsUnique();

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("AiNexus.Modules.Inference.GenerationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssistantMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActiveOwnerId")
                        .IsUnique()
                        .HasFilter("[ActiveOwnerId] IS NOT NULL");

                    b.HasIndex("AssistantMessageId");

                    b.HasIndex("UserMessageId");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.HasIndex("OwnerId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("GenerationRuns", "inference");
                });

            modelBuilder.Entity("AiNexus.Modules.Inference.ModelInvocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "CreatedAt");

                    b.ToTable("ModelInvocations", "inference");
                });

            modelBuilder.Entity("AiNexus.Modules.Inference.ModelProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("ContextTokens")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("int");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsUsage")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ModelProfiles", "inference");
                });

            modelBuilder.Entity("AiNexus.Modules.Inference.RunEvent", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Delta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("RunId", "Sequence");

                    b.ToTable("RunEvents", "inference");
                });

            modelBuilder.Entity("AiNexus.Modules.Knowledge.ConversationKnowledge", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConversationId", "CollectionId");

                    b.HasIndex("CollectionId");

                    b.ToTable("ConversationCollections", "knowledge");
                });

            modelBuilder.Entity("AiNexus.Modules.Knowledge.DocumentPage", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Extraction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId", "PageNumber");

                    b.ToTable("DocumentPages", "knowledge");
                });

            modelBuilder.Entity("AiNexus.Modules.Knowledge.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmbeddingJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingProfile")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "Ordinal")
                        .IsUnique();

                    b.ToTable("Chunks", "knowledge");
                });

            modelBuilder.Entity("AiNexus.Modules.Knowledge.KnowledgeCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("Collections", "knowledge");
                });

            modelBuilder.Entity("AiNexus.Modules.Knowledge.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EmbeddingProfile")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Warning")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("CollectionId", "Status");

                    b.ToTable("Documents", "knowledge");
                });

            modelBuilder.Entity("AiNexus.Modules.Knowledge.MessageCitation", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("MessageId", "Number");

                    b.HasIndex("DocumentId");

                    b.ToTable("MessageCitations", "knowledge");
                });

            modelBuilder.Entity("AiNexus.Modules.Library.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "UpdatedAt");

                    b.ToTable("PromptTemplates", "library");
                });

            modelBuilder.Entity("AiNexus.Modules.Operations.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(12000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Result")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("AuditEvents", "operations");
                });

            modelBuilder.Entity("AiNexus.Modules.Operations.BackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActiveKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("bit");

                    b.Property<int>("CompletedUnits")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TotalUnits")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ActiveKey")
                        .IsUnique()
                        .HasFilter("[ActiveKey] IS NOT NULL");

                    b.HasIndex("ResourceId");

                    b.HasIndex("OwnerId", "CreatedAt");

                    b.HasIndex("Status", "LeaseUntil", "CreatedAt");

                    b.ToTable("BackgroundJobs", "operations");
                });

            modelBuilder.Entity("AiNexus.Modules.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects", "projects");
                });

            modelBuilder.Entity("AiNexus.Modules.Projects.ProjectTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTemplates", "projects");
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.RoleGroupFeature", b =>
                {
                    b.HasOne("AiNexus.Modules.AccessControl.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.AccessControl.RoleGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.RoleGroupRole", b =>
                {
                    b.HasOne("AiNexus.Modules.AccessControl.RoleGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.AccessControl.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.AccessControl.UserRole", b =>
                {
                    b.HasOne("AiNexus.Modules.AccessControl.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Identity.NexusUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Administration.AdministratorBootstrap", b =>
                {
                    b.HasOne("AiNexus.Modules.Identity.NexusUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Administration.GroupModelPolicy", b =>
                {
                    b.HasOne("AiNexus.Modules.AccessControl.RoleGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Artifacts.Artifact", b =>
                {
                    b.HasOne("AiNexus.Modules.Collaboration.WorkspaceResource", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AiNexus.Modules.Conversations.Message", null)
                        .WithMany()
                        .HasForeignKey("SourceMessageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AiNexus.Modules.Artifacts.ArtifactRevision", b =>
                {
                    b.HasOne("AiNexus.Modules.Artifacts.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Identity.NexusUser", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Attachments.Attachment", b =>
                {
                    b.HasOne("AiNexus.Modules.Identity.NexusUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Attachments.AttachmentReference", b =>
                {
                    b.HasOne("AiNexus.Modules.Attachments.Attachment", null)
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Collaboration.WorkspaceResource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Attachments.MessageAttachment", b =>
                {
                    b.HasOne("AiNexus.Modules.Attachments.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Conversations.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("AiNexus.Modules.Collaboration.ResourceGroup", b =>
                {
                    b.HasOne("AiNexus.Modules.AccessControl.RoleGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Collaboration.WorkspaceResource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Collaboration.ResourceMember", b =>
                {
                    b.HasOne("AiNexus.Modules.Collaboration.WorkspaceResource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Identity.NexusUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Collaboration.WorkspaceResource", b =>
                {
                    b.HasOne("AiNexus.Modules.Identity.NexusUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Collaboration.WorkspaceResource", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AiNexus.Modules.Conversations.Conversation", b =>
                {
                    b.HasOne("AiNexus.Modules.Identity.NexusUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AiNexus.Modules.Conversations.ConversationLabel", b =>
                {
                    b.HasOne("AiNexus.Modules.Conversations.Conversation", null)
                        .WithMany("Labels")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Conversations.Message", b =>
                {
                    b.HasOne("AiNexus.Modules.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Conversations.Message", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AiNexus.Modules.Identity.NexusUser", b =>
                {
                    b.OwnsOne("AiNexus.Modules.Identity.UserPreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("NexusUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("AutoFollow")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true);

                            b1.Property<string>("DefaultModelId")
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)");

                            b1.Property<string>("DefaultReasoningEffort")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasDefaultValue("auto");

                            b1.Property<string>("Density")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasDefaultValue("comfortable");

                            b1.Property<bool>("EnterToSend")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true);

                            b1.Property<bool>("NotifyOnCompletion")
                                .HasColumnType("bit");

                            b1.Property<int>("ReadingFontSize")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(17);

                            b1.Property<double>("ReadingLineHeight")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(1.8);

                            b1.Property<string>("ReadingWidth")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasDefaultValue("standard");

                            b1.Property<bool>("ReducedMotion")
                                .HasColumnType("bit");

                            b1.Property<bool>("SaveLocalDrafts")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true);

                            b1.Property<int>("SidebarWidth")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(264);

                            b1.Property<string>("Theme")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)");

                            b1.HasKey("NexusUserId");

                            b1.ToTable("UserPreferences", "identity");

                            b1.WithOwner()
                                .HasForeignKey("NexusUserId");
                        });

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Inference.GenerationRun", b =>
                {
                    b.HasOne("AiNexus.Modules.Conversations.Message", null)
                        .WithMany()
                        .HasForeignKey("AssistantMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Identity.NexusUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Conversations.Message", null)
                        .WithMany()
                        .HasForeignKey("UserMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Inference.ModelInvocation", b =>
                {
                    b.HasOne("AiNexus.Modules.Identity.NexusUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Inference.RunEvent", b =>
                {
                    b.HasOne("AiNexus.Modules.Inference.GenerationRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Knowledge.ConversationKnowledge", b =>
                {
                    b.HasOne("AiNexus.Modules.Knowledge.KnowledgeCollection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Knowledge.DocumentPage", b =>
                {
                    b.HasOne("AiNexus.Modules.Knowledge.KnowledgeDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Knowledge.KnowledgeChunk", b =>
                {
                    b.HasOne("AiNexus.Modules.Knowledge.KnowledgeDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Knowledge.KnowledgeCollection", b =>
                {
                    b.HasOne("AiNexus.Modules.Collaboration.WorkspaceResource", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Knowledge.KnowledgeDocument", b =>
                {
                    b.HasOne("AiNexus.Modules.Attachments.Attachment", null)
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AiNexus.Modules.Knowledge.KnowledgeCollection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AiNexus.Modules.Collaboration.WorkspaceResource", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Knowledge.MessageCitation", b =>
                {
                    b.HasOne("AiNexus.Modules.Knowledge.KnowledgeDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Conversations.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Library.PromptTemplate", b =>
                {
                    b.HasOne("AiNexus.Modules.Identity.NexusUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Operations.BackgroundJob", b =>
                {
                    b.HasOne("AiNexus.Modules.Identity.NexusUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiNexus.Modules.Collaboration.WorkspaceResource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AiNexus.Modules.Projects.Project", b =>
                {
                    b.HasOne("AiNexus.Modules.Collaboration.WorkspaceResource", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Projects.ProjectTemplate", b =>
                {
                    b.HasOne("AiNexus.Modules.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiNexus.Modules.Conversations.Conversation", b =>
                {
                    b.Navigation("Labels");
                });
#pragma warning restore 612, 618
        }
    }
}
