/** Built-in defaults; administrator-defined names are shared by navigation and page titles. */
export const FEATURE_NAMES: Readonly<Record<string, string>> = {
  dashboard: '總覽',
  chat: '對話',
  files: '檔案庫',
  projects: '專案',
  knowledge: '知識庫',
  artifacts: '成果文件',
  shared: '分享',
  quality: '品質評測',
  repositories: '程式庫',
  tasks: '背景任務',
  integrations: '資料來源',
  admin: '平台管理',
  monitoring: '即時監控',
  audit: '活動稽核',
  'logs.query': '系統日誌',
  'logs.detail': '日誌診斷詳情',
  'logs.export': '日誌匯出',
};
