<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="NetArchTest.eNhancedEdition" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/AiNexus.Host/AiNexus.Host.csproj" />
    <ProjectReference Include="../../src/AiNexus.Features/AiNexus.Features.csproj" />
    <ProjectReference Include="../../src/AiNexus.Platform/AiNexus.Platform.csproj" />
  </ItemGroup>
</Project>
