import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  InjectionToken,
  input,
} from '@angular/core';
import {
  type IconNode,
  ThumbsUp,
  Files,
  Bell,
  LoaderCircle,
  ThumbsDown,
  Share2,
  Plus,
  Star,
  Archive,
  ArchiveRestore,
  Upload,
  Paperclip,
  Library,
  PanelsTopLeft,
  SquareTerminal,
  LayoutDashboard,
  GitBranch,
  Globe,
  CircleDollarSign,
  Database,
  SlidersHorizontal,
  Tag,
  Search,
  PanelLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  Ellipsis,
  Copy,
  Pencil,
  RefreshCw,
  Square,
  X,
  Check,
  FileText,
  MessageSquare,
  MessageSquareText,
  ClipboardList,
  ScrollText,
  ChevronUp,
  ChevronDown,
  CircleHelp,
  Lightbulb,
  Info,
  Trash2,
  LockKeyhole,
  Download,
  FolderKanban,
  ListTodo,
  Workflow,
  ChartNoAxesCombined,
  Maximize2,
  Minimize2,
  User,
  LogOut,
  Settings2,
  ShieldCheck,
  History,
  ArrowLeft,
  Eye,
  Image as ImageIcon,
  ExternalLink,
  Filter,
  Play,
  Calendar,
  Activity,
} from 'lucide';
import { LucideDynamicIcon } from '@lucide/angular';

// Semantic names keep business templates independent of the icon vendor.
// Import curated SVG data; a single Angular renderer avoids retaining per-icon component metadata.
const icons: Record<string, IconNode> = {
  activity: Activity,
  image: ImageIcon,
  files: Files,
  bell: Bell,
  loading: LoaderCircle,
  external: ExternalLink,
  'thumb-up': ThumbsUp,
  'thumb-down': ThumbsDown,
  share: Share2,
  plus: Plus,
  star: Star,
  archive: Archive,
  restore: ArchiveRestore,
  upload: Upload,
  paperclip: Paperclip,
  library: Library,
  command: SquareTerminal,
  workspace: PanelsTopLeft,
  dashboard: LayoutDashboard,
  git: GitBranch,
  globe: Globe,
  money: CircleDollarSign,
  database: Database,
  sliders: SlidersHorizontal,
  tag: Tag,
  search: Search,
  sidebar: PanelLeft,
  arrow: ArrowUp,
  down: ArrowDown,
  chevron: ChevronRight,
  left: ChevronLeft,
  more: Ellipsis,
  copy: Copy,
  edit: Pencil,
  repeat: RefreshCw,
  refresh: RefreshCw,
  stop: Square,
  close: X,
  check: Check,
  document: FileText,
  lines: MessageSquare,
  chat: MessageSquareText,
  audit: ClipboardList,
  logs: ScrollText,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  tour: CircleHelp,
  idea: Lightbulb,
  info: Info,
  trash: Trash2,
  lock: LockKeyhole,
  download: Download,
  projects: FolderKanban,
  tasks: ListTodo,
  integrations: Workflow,
  chart: ChartNoAxesCombined,
  maximize: Maximize2,
  minimize: Minimize2,
  user: User,
  logout: LogOut,
  settings: Settings2,
  shield: ShieldCheck,
  history: History,
  back: ArrowLeft,
  eye: Eye,
  filter: Filter,
  play: Play,
  calendar: Calendar,
  columns: SlidersHorizontal,
};
/** Optional feature icons stay in their lazy feature bundle. */
export const EXTRA_ICONS = new InjectionToken<Readonly<Record<string, IconNode>>>('Feature icons');
@Component({
  selector: 'nx-icon',
  imports: [LucideDynamicIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<svg [lucideIcon]="icon()" [size]="20" [strokeWidth]="1.65" aria-hidden="true"></svg>',
  styles:
    ':host{display:inline-flex;align-items:center;justify-content:center;width:20px;height:20px;flex:none;line-height:0;vertical-align:middle}svg{display:block;width:100%;height:100%}',
})
export class Icon {
  private readonly extra = inject(EXTRA_ICONS, { optional: true });
  readonly name = input.required<string>();
  readonly icon = computed(() => ({
    name: this.name(),
    node: this.extra?.[this.name()] ?? icons[this.name()] ?? Info,
  }));
}
