// Fixed public operation hints; kept in sync with PublicErrorCatalog.cs.
export const publicErrorHints: Readonly<Record<string, string>> = {
  https_required: '此工作區需要 HTTPS 安全連線。',
  identity_changed: '測試身分已結束，請重新載入工作區。',
  authentication_required: '請先登入工作區。',
  access_denied: '沒有存取此資料的權限。',
  not_found: '找不到資料。',
  invalid_request: '請求格式不正確。',
  csrf_invalid: '安全驗證已失效，請重新載入頁面。',
  rate_limited: '操作過於頻繁，請稍後再試。',
  log_filter_invalid: '日誌篩選格式或範圍超過限制。',
  log_text_range: '文字搜尋限一天內。',
  log_cursor_invalid: '分頁已失效，請重新查詢。',
  log_not_found: '找不到此日誌。',
  log_export_limit: '匯出資料量超過限制，請縮小範圍。',
  log_export_cursor: '匯出請使用完整時間範圍。',
  client_issue_invalid: '問題回報格式不正確。',
  request_too_large: '上傳內容超過大小上限。',
  database_name: '本初始化指令只允許建立或更新 AiNexus 專用資料庫。',
  test_admin_read_only: '測試身分期間只能檢視管理功能；請先返回管理者再異動帳號與授權。',
  feature_forbidden: '你的角色目前沒有使用此功能的權限，請聯絡管理員。',
  invalid_search: '搜尋條件不正確。',
  invalid_storage_limit: '容量上限需為 0 至 1,000,000 GB 的整數 bytes；留空則使用群組或預設容量。',
  invalid_model_policy: '群組容量上限不正確。',
  invalid_order: '排序值必須介於 0 與 10000。',
  invalid_audit_filter: '稽核篩選條件不正確。',
  invalid_access_id: '識別碼使用小寫英文、數字、底線與連字號，最多 64 字元。',
  invalid_access_ids: '授權清單過長或有重複。',
  invalid_access_name: '請輸入 120 字元內的名稱。',
  unknown_access_id: '清單包含不存在的角色、群組或功能。',
  admin_resource_not_found: '找不到此管理項目。',
  admin_lockout: '此變更會撤銷你的管理權限。請先由另一位管理員處理。',
  admin_required: '需要平台管理權限。',
  model_group_forbidden: '此模型不在你的個人或群組授權範圍。',
  model_token_quota:
    '此模型今日可用 token 不足（包含輸入、輸出與待結算預留）。請縮短提問、切換模型或聯絡管理員；台北時間每日 08:00 重設。',
  export_format_invalid: '支援 Word、PDF 或 Markdown 匯出。',
  pdf_export_busy: 'PDF 匯出正在忙碌，請稍後重試。',
  artifact_version_missing: '找不到此成果版本。',
  message_not_found: '找不到來源訊息。',
  artifact_limit: '個人成果文件已達 200 份上限。',
  project_access_required: '需要專案功能權限。',
  artifact_version_limit: '此文件最多保留 200 個版本；請建立副本繼續工作。',
  artifact_version_conflict: '此文件已被更新。你的編輯仍保留，請先查看最新版本再合併。',
  artifact_content_invalid: '成果內容需為 1 至 64,000 個字元，且不包含控制字元。',
  transform_input_invalid: '請選取 1 至 8,000 個字元，並使用支援的語言。',
  transform_action_invalid: '此段落操作不支援。',
  multipart_required: '請使用檔案上傳格式。',
  file_required: '每次上傳請提供一個檔案。',
  attachment_quota: '附件容量不足，請刪除未引用的檔案，或聯絡管理員調整個人容量上限。',
  invalid_file_name: '檔案名稱不正確或過長。',
  file_size_limit: '檔案過大。',
  file_size_mismatch: '上傳檔案內容不完整，請重新上傳。',
  attachment_upload_expired: '上傳已失效，請重新上傳。',
  attachment_not_found: '找不到這個附件。',
  document_processing_required: '掃描 PDF 尚未完成文字辨識，請等待附件處理完成後再送出。',
  attachment_total_limit: '這次附件總大小超過上限。',
  attachment_in_use: '已送出的附件由對話保留，無法單獨刪除。',
  file_type_unsupported:
    '支援圖片、PDF、DOCX、XLSX、PPTX 與 UTF-8 文字文件；不支援巨集、舊版 Office 二進位格式與壓縮檔。',
  invalid_image: '圖片內容與副檔名不符，請重新匯出圖片。',
  document_has_no_text: '文件沒有可讀文字。',
  document_unreadable: '無法讀取文件。請使用未加密的 PDF、DOCX、XLSX、PPTX，或 UTF-8 文字檔。',
  file_name_invalid: '檔名需為 1 至 180 個字元，不可包含路徑、控制字元或特殊符號。',
  file_not_found: '找不到這份檔案。',
  file_extension_changed: '重新命名時請保留原副檔名，以維持正確的預覽與格式識別。',
  file_name_changed: '檔名已被修改，請重新載入後再試。',
  file_filter_invalid: '檔案查詢條件不正確。',
  office_archive_limit: 'Office 文件解壓內容過大，請拆分後上傳。',
  office_macros_unsupported: '不接受巨集文件，請另存為不含巨集的格式。',
  presentation_slide_limit: '簡報需為 1 至 200 頁。',
  spreadsheet_string_limit: '試算表文字表過大，請拆分工作表。',
  spreadsheet_sheet_limit: '試算表需為 1 至 128 個工作表。',
  spreadsheet_cell_limit: '單一工作表最多 100,000 個非空儲存格。',
  invalid_price: '請檢查模型與工具價格、幣別、生效時間與計費方式。新價格只能由現在起生效。',
  price_exists: '此生效時間已有價格版本，請選擇新的時間。',
  invalid_spend_period: '查詢期間需為 1 至 366 天，並提供有效的時區。',
  conversation_not_found: '找不到這個對話。',
  resource_read_only: '此項目目前只有檢視權限。',
  invalid_resource_acl: '成員清單重複、過長或角色不正確。',
  owner_is_implicit: '擁有者已具有完整權限，不需加入成員清單。',
  unknown_resource_member: '清單包含未登入過的帳號或停用的群組。',
  invalid_resource_name: '名稱需為 1 至 120 個字元。',
  resource_not_found: '找不到此項目，或你已沒有存取權限。',
  resource_tasks_active: '此項目仍有背景任務，請先完成或取消，再刪除。',
  generation_active: '專案仍有正在生成的回答，請先完成或停止，再刪除。',
  instruction_too_long: '對話指令最多 4,000 字元。',
  invalid_backup: '備份格式不正確或內容過大（最多 400 則訊息）。',
  invalid_labels: '最多 5 個標籤，每個 1 至 24 字元。',
  invalid_query: '搜尋條件不正確。',
  conversation_archived: '請先還原封存對話，再繼續提問。',
  prompt_required: '請輸入訊息。',
  invalid_parent: '上文必須是此對話中已結束的回答。',
  invalid_title: '標題需為 1 至 120 個字元。',
  invalid_dashboard_scope: '檢視範圍不正確。',
  dashboard_access_denied: '只有管理員可檢視平台總覽。',
  invalid_password: '本地密碼需為 12–128 個字元，可使用長句與密碼管理器。',
  authentication_mode: '此工作區未使用 Windows 整合驗證。',
  invalid_credentials: '帳號、密碼或登入方式不正確，或帳號暫時無法登入。',
  test_identity_nested: '請先返回原管理者，再切換其他身分。',
  test_reason_required: '請填寫 4–240 字元的測試目的。',
  user_not_found: '找不到可測試的使用者。',
  test_identity_same: '請選擇另一位使用者。',
  test_source_revoked: '原管理者登入或權限已失效，請重新登入。',
  test_session_invalid: '測試登入已失效。',
  session_revoked: '登入已失效，請重新登入工作區。',
  windows_sid_required: '無法取得 AD SID，請確認登入設定。',
  windows_account_required: 'Windows 帳號資料不完整。',
  ad_binding_conflict: 'AD 身分與已連結帳號不一致，請聯絡管理員。',
  login_method_disabled: '此使用者已停用，或未允許 AD 驗證。',
  invalid_theme: '請選擇淺色、深色或跟隨系統。',
  invalid_model: '模型識別碼過長。',
  model_not_allowed: '偏好的模型未經伺服器核准。',
  ad_sid_required: 'AD 帳號缺少 SID，無法建立工作區。',
  ad_invalid_credentials: 'AD 帳號或密碼不正確，或此帳號無法登入。',
  invalid_settings: '個人設定超出允許範圍，請重新選擇。',
  invalid_account:
    '登入帳號需為 1–64 個字元，只能使用字母、數字、點、底線與連字號。AD 請填目錄中的帳號，不含網域。',
  invalid_user: '請輸入姓名與有效角色。',
  invalid_login_methods: '請至少設定一種登入方式，並填寫對應的登入帳號。',
  local_password_required: '首次啟用本地登入時，請設定密碼。',
  account_exists: '此登入帳號已由其他使用者使用或保留。',
  ad_binding_immutable: '已連結的 AD 身分不能換綁其他帳號；請建立另一位使用者。',
  invalid_roles: '選取的角色已不存在，請重新載入。',
  context_budget_exceeded: '提問超過此模型的上下文預算，請縮短內容或選擇較大上下文的模型。',
  invalid_history: '對話分支資料不完整。',
  vision_not_supported: '目前模型不支援圖片，請切換支援圖片的模型，或移除圖片附件。',
  chat_access_revoked: '對話功能權限已撤銷。',
  google_response_blocked: 'Google AI 未完成此回答，請調整提問後重試。',
  google_quota_exceeded: 'Google AI 額度或速率受限，請稍後重試。',
  input_too_long: '訊息超過字數上限。',
  evaluation_configuration_changed: '模型設定已變更；請建立新的任務，避免混用不同設定的結果。',
  task_input_too_long: '處理內容過長，請縮小選取範圍。',
  subscription_limit: '事件連線數已達上限，請關閉重複的分頁後重試。',
  invalid_cursor: '事件序號不正確。',
  run_not_found: '找不到這次生成。',
  idempotency_key_required: '請提供 16 至 80 字元的 Idempotency-Key。',
  idempotency_conflict: '此提交識別碼已用於不同內容。',
  queue_full: '生成佇列已滿，請稍後再試。',
  knowledge_selection_changed: '知識來源剛剛已變更，請重新送出提問。',
  integration_feature_revoked: '資料來源功能已停用。',
  source_forbidden: '你的群組沒有查詢此資料來源的權限。',
  source_identity_missing: '目前帳號缺少可對應來源授權的身分。',
  source_search_invalid: '請輸入 2 至 120 個字元並選擇此來源支援的類型。',
  source_id_invalid: '來源識別碼不正確。',
  source_record_missing: '找不到此資料，或原系統已撤銷你的權限。',
  artifact_feature_required: '匯入快照需要成果文件功能。',
  source_changed: '來源版本已更新，請重新閱讀後再匯入。',
  chat_feature_required: '需要對話功能權限。',
  source_chat_too_long:
    '本文超過可直接帶入對話的長度，請改選取一段文字複製到聊天，或先儲存成果再分段處理。',
  source_unknown: '找不到此資料來源。',
  source_body_too_large: '來源內容未公開或超過 16,000 字元，請至原系統閱讀完整內容。',
  index_source_changed: '文件或索引狀態已改變，請重新建立索引。',
  pdf_page_limit: 'PDF 頁數超過處理上限，請先拆分文件。',
  document_too_large: '文件文字超過處理上限，請拆分文件。',
  description_too_long: '知識庫說明最多 2000 個字元。',
  collection_limit: '個人知識庫數量已達上限。',
  document_not_indexed: '只有知識庫文件需要重新索引。',
  job_active: '此文件仍在處理中。',
  document_limit: '此知識庫的文件數量已達上限。',
  document_not_found: '找不到此文件，或你已沒有存取權限。',
  embeddings_disabled: '目前採用全文檢索，未啟用語意向量。',
  embedding_daily_quota: '今日索引、語意查詢與重排次數已達系統上限，請稍後重試。',
  profile_retired: '已退役的索引無法重建。',
  profile_not_building: '只能啟用重建中的索引。',
  profile_incomplete: '索引覆蓋率未達 100%，或仍有處理中的文件，請先完成重建。',
  profile_not_retired: '只能清除已退役索引的向量。',
  profile_not_found: '找不到這個檢索索引。',
  document_pages_missing: '文件尚無完整逐頁文字，請重新上傳資料後再重建。',
  chunker_configuration_invalid: '索引切段設定快照無效，請重新建立 profile。',
  chunker_version_unsupported: '此切段器版本已不受支援，請先重建並啟用新 profile。',
  knowledge_collection_limit: '每次最多使用三個不同知識庫。',
  knowledge_access_revoked: '知識庫功能權限已撤銷，請重新載入對話。',
  knowledge_source_changed: '知識來源已改變，請重新送出提問。',
  knowledge_query_invalid: '查詢需為 1 至 2000 個字元。',
  retrieval_mode_invalid: '檢索模式不正確。',
  embedding_profile_changed: '檢索索引已切換，請重新送出提問。',
  table_row_too_long: '表格單列超過片段上限，請先拆分表格欄位。',
  document_not_editable_text: '只有以純文字建立的來源可以編輯。',
  document_processing: '來源仍在處理，請等待完成或停止處理後再編輯。',
  text_title_invalid: '來源名稱不可包含路徑或特殊符號。',
  text_version_changed: '來源已被其他人修改。請重新開啟編輯器，再合併你的內容。',
  invalid_prompt_template: '範本標題最多 80 字元，內容最多 12,000 字元，皆不可空白。',
  template_limit: '個人範本最多 100 個。',
  template_not_found: '找不到這個範本。',
  notification_cursor_invalid: '通知清單已變更，請重新整理。',
  notification_cursor_required: '請提供本次通知清單的時間。',
  job_not_found: '找不到這個背景任務。',
  job_not_retryable: '只有失敗或已取消的任務可以重試。',
  job_retry_limit: '此任務已嘗試六次。請確認設定後重新建立來源。',
  job_handler_missing: '此任務類型已停用。',
  job_changed: '任務狀態已改變，請重新載入。',
  project_limit: '個人專案已達 100 個上限。',
  project_conflict: '專案設定已被修改，請重新載入後合併；目前輸入仍保留。',
  project_file_limit: '專案最多 50 份文件。',
  project_template_invalid: '範本名稱最多 80 字元，內容最多 12,000 字元，皆不可空白。',
  template_missing: '找不到此範本。',
  chat_access_required: '需要對話權限才能開啟專案對話。',
  project_files_pending: '專案仍有文件待完成辨識，請到專案檢視進度或移除不需要的文件。',
  project_context_limit: '專案參考文字超過 12,000 字元或 100 頁，請精簡參考文件或改用知識庫檢索。',
  conversation_missing: '找不到此對話。',
  project_archived: '請先還原封存專案，再進行此操作。',
  project_settings_invalid: '說明最多 2,000 字元，共用指示最多 4,000 字元。',
  evaluation_access_revoked: '你的品質評測功能已停用。',
  evaluation_run_missing: '找不到原始評測。',
  feedback_invalid: '回饋格式不正確，補充說明最多 2,000 字元。',
  feedback_answer_pending: '請等回答結束再提供回饋。',
  evaluation_set_conflict: '題庫已被其他人修改，請重新載入後合併。目前輸入仍保留。',
  evaluation_set_limit: '個人評測集已達 100 個。',
  evaluation_variants_invalid: '請設定 1 至 3 個名稱不同的比較方案，指令最多 4,000 字元。',
  evaluation_active: '你已有處理中的評測，請先完成或取消。',
  evaluation_run_limit: '個人評測已達 500 次保留上限。',
  review_invalid: '人工評分介於 1 至 5，說明最多 2,000 字元。',
  quality_item_missing: '找不到此回饋或評測項目。',
  evaluation_cases_invalid:
    '題庫需有 1 至 20 題；問題與參考答案各最多 4,000 字元，關鍵字各最多 20 個、每個 80 字元。',
  retrieval_corpus_invalid: '相關文件必須已完成索引且位於選取的知識庫。',
  retrieval_pages_invalid: '驗收集包含不存在的文件頁碼。',
  retrieval_evaluation_active: '已有處理中的檢索評測，請先完成或取消。',
  retrieval_evaluation_limit: '個人檢索評測已達 500 次保留上限。',
  retrieval_evaluation_missing: '找不到此檢索評測。',
  retrieval_evaluation_changed: '索引、文件版本或檢索設定已變更，請重新建立評測以取得可比較結果。',
  retrieval_evaluation_invalid: '請提供名稱、1 至 3 個知識庫及 1 至 20 題驗收集。',
  repository_diff_limit: '變更內容超過 256 KB，請縮小 commit 區間。',
  repository_diff_not_text: '變更內容不是 UTF-8 文字，無法 review。',
  review_purpose_invalid: '請選擇整體檢閱、變更摘要或內容誤植。',
  review_model_context_small:
    '此模型的上下文不足以檢閱並彙整變更，請選擇更大的模型或減少補充重點。',
  review_empty_range: '起點與終點必須是不同的 commit。',
  review_request_invalid: 'Review 重點最多 2,000 字元，請使用有效的請求識別碼。',
  review_not_found: '找不到這份 review。',
  review_host_changed: '程式庫主機已變更，請在目前的連線建立新的 review。',
  review_snapshot_unsupported: '此 review 快照版本目前無法處理，請建立新的 review。',
  review_no_changes: '此 commit 或區間沒有可檢閱的變更。',
  review_segment_limit: '變更需要超過 60 個區段，請縮小區間或選擇更大的模型。',
  review_access_revoked: '你的程式庫功能已停用。',
  gitea_diff_unsupported:
    'Gitea 未回傳完整的 diff。區間 review 需要支援 compare output=diff 的 Gitea 版本。',
  invalid_gitea_token: '請輸入有效的 Gitea 個人存取權杖。',
  invalid_page: '分頁不正確。',
  repository_empty: '此程式庫尚無提交版本。',
  repository_not_directory: '請選擇資料夾。',
  repository_file_limit: '僅支援上限內的文字檔案，不支援目錄、LFS 與二進位檔。',
  repository_not_text: '此檔案不是可辨識的 UTF-8 文字檔。',
  gitea_not_connected: '請先連線自己的 Gitea 帳號。',
  gitea_reconnect_required: '授權無法解密，請重新連線 Gitea。',
  invalid_repository: '程式庫名稱不正確。',
  invalid_commit: '請選擇固定的 commit 版本。',
  invalid_repository_path: '檔案路徑不正確。',
  share_invalid: '請選擇 1 至 20 位其他使用者，分享期限介於 1 小時與 30 天。',
  share_recipient_unknown: '只能分享給已登入過平台的使用者。',
  share_limit: '有效分享已達 100 個，請撤銷不再使用的分享。',
  share_generation_active: '請先等待或停止回答，再分享完整內容。',
  share_history_invalid: '對話分支資料不完整。',
  share_history_limit: '單次分享最多 100 則訊息，請改分享整理後的成果文件。',
  share_content_limit: '分享內容過長，請改分享整理後的成果文件。',
  share_unavailable: '分享不存在、已到期或撤銷，或你的帳號不在收件者清單中。',
  web_query_too_long: '網路搜尋提問最多 2000 個字元，請簡化查詢。',
  web_search_pending_or_failed: '這次搜尋正在處理或未完成。請重新提交新的訊息。',
  web_search_daily_quota: '今日網路搜尋已達上限。',
};
