using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AiNexus.BuildingBlocks;

/// <summary>Schema documentation is model metadata, checked at build/test time and deployed by EF.</summary>
public static class DatabaseDescriptions
{
    private static readonly IReadOnlyDictionary<string, string> Tables = new Dictionary<string, string>
    {
        ["Users"] = "使用者身分、AD SID 綁定、可用登入方式與工作階段撤銷版本；不保存 AD 密碼。",
        ["UserPreferences"] = "使用者個人外觀、閱讀、對話操作與通知偏好；不含服務密鑰。",
        ["Roles"] = "可分派給使用者的角色；停用後不再提供有效授權。",
        ["RoleGroups"] = "角色所加入的功能群組，集中管理功能及模型政策。",
        ["Features"] = "模組註冊的功能入口、顯示名稱、路由及啟用狀態。",
        ["UserRoles"] = "使用者與角色的分派關聯。",
        ["RoleGroupRoles"] = "角色與功能群組的授權關聯。",
        ["RoleGroupFeatures"] = "功能群組與功能的授權關聯；有效功能取聯集。",
        ["AdministratorBootstraps"] = "管理者首次啟動授權的永久標記，防止撤銷後重新授權。",
        ["UserModelPolicies"] = "使用者的模型白名單與各模型每日 token 覆寫政策。",
        ["GroupModelPolicies"] = "功能群組的模型白名單、各模型每日 token 及附件空間限制。",
        ["Conversations"] = "使用者私人對話、目前訊息分支、收藏封存與自訂指令。",
        ["Messages"] = "對話訊息樹；提問、回答、重新生成與編輯保留各版本。",
        ["ConversationLabels"] = "使用者對話的分類標籤。",
        ["GenerationRuns"] = "聊天生成的持久狀態、冪等請求、執行租約、回答及用量。",
        ["RunEvents"] = "生成事件的有序 SSE 重播紀錄；完整生成狀態以 GenerationRuns 為準。",
        ["ModelProfiles"] = "核准模型的能力、上下文與輸出限制。",
        ["ModelInvocations"] = "文字、OCR、embedding 等模型呼叫的狀態與實際用量。",
        ["ModelPrices"] = "依供應商、模型、幣別及成本類型保存的不可變價格版本。",
        ["ModelCharges"] = "各呼叫當時的價格與用量快照；未知費用保持空值。",
        ["WebSearches"] = "使用者明確啟用的網路搜尋、冪等識別、結果與費用。",
        ["AuditEvents"] = "操作與管理異動稽核；保存實際管理者及有效身分，不記錄密碼或私密內容。",
        ["BackgroundJobs"] = "文件索引與評測等背景工作的租約、進度、重試與取消狀態。",
        ["Attachments"] = "站外附件原檔的 metadata、儲存識別、擷取文字及生命週期；不保存原始 bytes。",
        ["MessageAttachments"] = "訊息與附件的關聯及呈現順序。",
        ["ResourceAttachments"] = "知識庫或專案資源與附件的引用關聯。",
        ["PromptTemplates"] = "使用者私人提示詞範本。",
        ["Resources"] = "共用資源的擁有者、種類、階層及版本；作為資料 ACL 邊界。",
        ["ResourceMembers"] = "資源對具名使用者授予的閱讀或編輯權限。",
        ["ResourceGroups"] = "資源對功能群組授予的唯讀權限。",
        ["ShareLinks"] = "分享版本快照、有效期限、附件選項及撤銷狀態。",
        ["ShareRecipients"] = "分享的具名收件人；與原資源 ACL 分開判定。",
        ["Collections"] = "知識庫的資料資源關聯及索引資訊。",
        ["Documents"] = "知識庫文件的原始附件、分析／索引狀態與 embedding profile。",
        ["DocumentPages"] = "文件逐頁擷取的文字、頁碼與 OCR 結果。",
        ["Chunks"] = "結構化檢索片段與 profile 專屬切段版本；查詢先套用資料 ACL。",
        ["EmbeddingProfiles"] = "向量空間及切段規則的不可變快照；同時最多一個 active。",
        ["ChunkEmbeddings768"] = "768 維原生向量、片段關聯與 profile 內容快取。",
        ["ChunkEmbeddings1024"] = "1024 維原生向量、片段關聯與 profile 內容快取。",
        ["ConversationCollections"] = "對話選定的知識庫來源關聯。",
        ["MessageCitations"] = "回答生成當時的知識引用、文件頁碼與摘要快照。",
        ["Artifacts"] = "使用者保存的成果文件與目前版本。",
        ["ArtifactRevisions"] = "成果文件不可變版本、內容與作者。",
        ["SourceReferences"] = "外部來源匯入的識別、來源版本與匯入時間。",
        ["Projects"] = "專案資源、共用指令及範本版本。",
        ["ProjectTemplates"] = "專案建立範本與預設指令。",
        ["MessageFeedback"] = "使用者對 AI 回答的私人評分與意見。",
        ["EvaluationSets"] = "評測題庫、固定測試案例與版本。",
        ["EvaluationRuns"] = "評測執行的題庫與模型設定快照、背景工作與狀態。",
        ["EvaluationResults"] = "各案例／模型組合的輸出、指標、用量與人工覆核結果。",
        ["Notifications"] = "使用者個人通知、版本化導向、閱讀狀態與事件去重鍵。",
        ["RepositoryReviews"] = "固定 commit 或區間 diff 的私人 review、模型設定指紋與背景任務。",
        ["RepositoryReviewResults"] = "Review 各區段的持久結果及用量；重試沿用已完成區段。",
        ["RepositoryConnections"] = "使用者個人的 Gitea 連線及 Data Protection 保護的存取 token。",
        ["RepositoryImports"] = "程式庫文件匯入所固定的主機、repository、commit 與檔案路徑。",
    };
    private static readonly IReadOnlyDictionary<string, string> Columns = new Dictionary<string, string>
    {
        ["InLibrary"] = "是否由個人檔案庫獨立保留原檔；移除對話或知識索引不會刪除保留的檔案。",
        ["Id"] = "資料的主鍵識別碼。", ["Account"] = "登入身分顯示帳號；AD 連結後保存目錄提供的帳號。",
        ["Sid"] = "AD 的不可變 SID；尚未綁定 AD 的手動帳號使用 managed: 識別碼。",
        ["DisplayName"] = "使用者或模型的介面顯示名稱。", ["Enabled"] = "是否啟用；停用不刪除歷史資料。",
        ["AdAccount"] = "預先配置的 AD 帳號正規化值；唯一、不含網域，驗證成功後以 SID 固定綁定。",
        ["AdEnabled"] = "是否允許使用 AD／Windows 整合驗證登入。",
        ["LocalAccount"] = "本地登入帳號正規化值；唯一且不區分大小寫。",
        ["LocalEnabled"] = "是否允許本地密碼登入；與 AD 驗證獨立。",
        ["PasswordHash"] = "本地密碼的 Argon2id PHC 雜湊，含版本、成本、隨機 salt 與衍生值；不可還原。",
        ["SecurityVersion"] = "登入政策或密碼變更時遞增，立即撤銷舊工作階段。",
        ["ProfileManaged"] = "姓名是否由管理者維護；開啟後 AD 目錄不覆寫姓名。",
        ["FailedLogins"] = "本地登入連續失敗次數，用於暫時鎖定。",
        ["LockedUntil"] = "本地帳號暫時鎖定的到期時間；空值表示未鎖定。",
        ["LastSeenAt"] = "使用者最近登入／活動時間，採 UTC offset。",
        ["DeletedAt"] = "登入身分刪除時間；保留關聯與歷史資料。",
        ["OwnerId"] = "資料擁有者／有效操作身分的 Users 主鍵；用於私人資料隔離。",
        ["ActorId"] = "身分測試時實際發起操作的管理者；空值表示與 OwnerId 相同。",
        ["UserId"] = "關聯使用者的 Users 主鍵。", ["NexusUserId"] = "個人偏好對應使用者的主鍵與外鍵。",
        ["AuthorId"] = "建立此版本的使用者識別碼。", ["CreatedBy"] = "建立紀錄的使用者識別碼。",
        ["ReviewerId"] = "人工覆核者的使用者識別碼。", ["SubjectId"] = "操作所關聯的業務對象識別碼。",
        ["RoleId"] = "關聯角色的識別碼。", ["GroupId"] = "關聯功能群組的識別碼。", ["FeatureId"] = "關聯功能的識別碼。",
        ["Name"] = "業務物件的顯示名稱。", ["Title"] = "介面顯示標題。", ["Description"] = "業務物件的用途說明。",
        ["Route"] = "功能入口的本站路由；API 授權仍由後端政策判定。", ["SortOrder"] = "介面顯示順序；數值越小越前。",
        ["AllowedModelsJson"] = "模型白名單 JSON；群組取聯集，空值授予全部、空陣列不授權；個人白名單再限縮。",
        ["DailyTokenLimitsJson"] = "各模型每日輸入加輸出 token 上限 JSON；授權群組取最高值、留空不限，個人覆寫優先，UTC 午夜重設。",
        ["ReservedTokens"] = "生成預留的保守輸入加最大輸出 token；執行中或缺失 usage 時占用配額，未執行即取消釋放。",
        ["StoredAttachmentLimitBytes"] = "個人附件儲存上限，以 bytes 計；群組限制取最低值。",
        ["AttachmentLimitBytes"] = "管理者設定的個人容量上限 bytes；優先於群組，空值使用群組或預設 5 GB。",
        ["StorageKey"] = "站外原檔的不可變隨機識別碼；不含使用者路徑或檔名。",
        ["StorageState"] = "原檔儲存狀態 pending／ready／deleting；刪檔成功才釋放 metadata 與容量。",
        ["ProviderModelId"] = "送往指定供應商的原生模型識別碼，與核准路由識別碼分開保存。",
        ["DurationMilliseconds"] = "從請求建立至終止的總耗時毫秒；包括排隊、生成、取消與失敗。",
        ["GenerationMilliseconds"] = "從生成開始至終止的耗時毫秒；未開始的請求保持空值。",
        ["Theme"] = "外觀偏好：system、light 或 dark。", ["ReducedMotion"] = "是否減少動畫與動態效果。",
        ["DefaultModelId"] = "偏好的核准模型識別碼；空值使用伺服器預設。", ["DefaultReasoningEffort"] = "偏好的推理強度。",
        ["ReadingFontSize"] = "對話文字大小，以 CSS px 的偏好值記錄。", ["ReadingLineHeight"] = "對話閱讀行高倍率。",
        ["Density"] = "介面密度偏好。", ["SidebarWidth"] = "側欄寬度偏好。", ["ReadingWidth"] = "閱讀區寬度偏好。",
        ["EnterToSend"] = "是否以 Enter 送出提問；IME 組字不送出。", ["AutoFollow"] = "生成時是否跟隨最新回答。",
        ["SaveLocalDrafts"] = "是否在瀏覽器按使用者保存草稿。", ["NotifyOnCompletion"] = "是否在背景分頁提醒回答完成。",
        ["ConversationId"] = "關聯對話的識別碼。", ["MessageId"] = "關聯訊息的識別碼。",
        ["UserMessageId"] = "此次生成的使用者提問訊息識別碼。", ["AssistantMessageId"] = "此次生成的 AI 回答訊息識別碼。",
        ["ActiveLeafId"] = "對話目前顯示分支的最後訊息識別碼。", ["ParentId"] = "父訊息或父資源識別碼，用於分支或階層繼承。",
        ["Role"] = "訊息角色（user／assistant）或資源成員的閱讀／編輯權限。",
        ["Content"] = "訊息、版本或生成的文字內容。", ["Text"] = "文件頁面／片段的擷取文字。",
        ["SystemInstruction"] = "對話專用的回答指令。", ["Instructions"] = "專案共用指令。", ["Label"] = "分類標籤或階段的顯示文字。",
        ["IsFavorite"] = "是否標記收藏。", ["IsArchived"] = "是否封存對話；封存後不再接受新的生成。",
        ["IsDeleted"] = "是否邏輯刪除；不自動刪除歷史紀錄。", ["IsRevoked"] = "分享是否已撤銷。",
        ["RunId"] = "關聯生成或評測執行的識別碼。", ["ModelId"] = "核准模型的內部識別碼。",
        ["Provider"] = "模型或搜尋服務供應商識別碼。", ["Status"] = "業務執行狀態。", ["State"] = "業務物件的生命週期狀態。",
        ["Kind"] = "業務操作、資源或成本的種類。", ["Type"] = "事件的種類。", ["Operation"] = "模型呼叫或背景工作的操作類型。",
        ["ParametersJson"] = "執行參數的 JSON 快照，不含服務密鑰。", ["IdempotencyKey"] = "擁有者範圍內的冪等請求識別，避免重試重複處理。",
        ["RequestHash"] = "請求內容指紋，用於辨識冪等識別碼衝突。", ["ActiveOwnerId"] = "仍在執行的擁有者；filtered unique index 限制每人一個生成。",
        ["LastSequence"] = "最後已持久化的生成事件序號。", ["Sequence"] = "事件在同一生成中的遞增序號。", ["Delta"] = "生成文字增量或完整快照。",
        ["ExecutorId"] = "處理此次生成的伺服器程序識別碼。", ["LeaseExpiresAt"] = "生成 executor 租約的到期時間。",
        ["LeaseToken"] = "背景工作租約的 fencing token，防止過期 worker 提交。", ["LeaseUntil"] = "背景工作租約的到期時間。",
        ["ActiveKey"] = "仍在執行工作的唯一鍵，避免同一業務重複排程。", ["Attempt"] = "背景工作執行／重試次數。",
        ["Stage"] = "背景工作目前階段。", ["CompletedUnits"] = "已完成的真實工作單位數。", ["TotalUnits"] = "已知的總工作單位數；未知不表示百分比。",
        ["CancelRequested"] = "是否收到取消要求；不表示工作已停止。", ["ErrorCode"] = "對外安全的錯誤代碼，不含密碼或完整例外。",
        ["ErrorMessage"] = "經限制的錯誤說明。", ["Warning"] = "處理過程中的非致命提示。",
        ["CreatedAt"] = "資料建立時間，採 UTC offset。", ["UpdatedAt"] = "資料最後修改時間，採 UTC offset。",
        ["StartedAt"] = "工作開始執行時間。", ["FinishedAt"] = "工作結束時間。", ["At"] = "稽核事件發生時間。",
        ["Action"] = "稽核操作名稱。", ["Result"] = "稽核操作結果或失敗代碼。",
        ["DetailsJson"] = "稽核前後狀態或操作範圍 JSON；不含密碼、hash、token 或對話內容。",
        ["ContextTokens"] = "模型上下文容量，以 tokens 計。", ["MaxOutputTokens"] = "模型核准的最大輸出 tokens。",
        ["SupportsStreaming"] = "模型是否支援串流輸出。", ["SupportsUsage"] = "模型是否會回報實際用量。",
        ["InputTokens"] = "模型回報的輸入 tokens；未知保持空值。", ["OutputTokens"] = "模型回報的輸出 tokens；未知保持空值。",
        ["CachedInputTokens"] = "模型回報的快取輸入 tokens。", ["ReasoningTokens"] = "模型回報的推理 tokens。",
        ["UsageComplete"] = "本次呼叫是否有完整且可計費的實際用量。", ["ElapsedMs"] = "執行耗時，以毫秒計。",
        ["Currency"] = "費用幣別代碼；不同幣別不可直接合計。", ["Amount"] = "此呼叫的已知費用；未知保持空值。",
        ["EffectiveAt"] = "此價格版本開始生效的時間。", ["InputPerMillion"] = "每百萬輸入 tokens 的單價。",
        ["CachedInputPerMillion"] = "每百萬快取輸入 tokens 的單價。", ["OutputPerMillion"] = "每百萬輸出 tokens 的單價。",
        ["PerRequest"] = "每次呼叫的固定單價。", ["RequestCharge"] = "搜尋服務每次請求的費用。", ["PriceId"] = "此呼叫採用的不可變價格版本。",
        ["ResultsJson"] = "搜尋結果的 JSON 快照。", ["Outcome"] = "搜尋或處理操作的結果分類。",
        ["AttachmentId"] = "引用的附件識別碼。", ["FileName"] = "原始附件檔名，不作為伺服器儲存路徑。",
        ["ContentType"] = "核准的 MIME 型別。", ["Size"] = "原始附件大小，以 bytes 計。", ["Data"] = "原始附件二進位內容；不在 wwwroot 公開。",
        ["ExtractedText"] = "附件分析後的文字。", ["Extraction"] = "附件文字擷取方法或結果。",
        ["ResourceId"] = "關聯或稽核對象的業務資源識別碼。", ["ProjectId"] = "關聯專案的識別碼。",
        ["CollectionId"] = "關聯知識庫的識別碼。", ["DocumentId"] = "關聯知識文件的識別碼。",
        ["PageNumber"] = "文件頁碼，從 1 開始。", ["PageCount"] = "文件總頁數。", ["ChunkCount"] = "文件已建立的檢索片段數。",
        ["Ordinal"] = "同一父物件內的呈現順序。", ["Number"] = "回答引用的順序編號。", ["Excerpt"] = "檢索或引用時保存的文字摘要。",
        ["SearchId"] = "全文索引使用的整數唯一鍵；保留未來 ANN 映射。",
        ["ProfileId"] = "向量空間及切段版本的 EmbeddingProfiles 外鍵。",
        ["ChunkId"] = "向量對應的結構化片段 Guid 識別碼。",
        ["StartPage"] = "片段開始的原始文件頁碼。", ["EndPage"] = "片段結束的原始文件頁碼。",
        ["HeadingPath"] = "由標題階層組成的結構路徑。", ["ContentHash"] = "實際向量輸入（文件名稱、標題路徑與本文）的 SHA-256。",
        ["TokenEstimate"] = "依 CJK 與其他字元比例估算的片段 token 數。",
        ["Vector"] = "L2 正規化的 float32 向量；SQL Server 使用 VECTOR 型別。",
        ["Key"] = "供應商、模型、維度及輸入／切段規則的唯一指紋。",
        ["Dimensions"] = "向量維度，限已建立資料表的 allowlist。",
        ["Model"] = "建立此向量空間時的模型識別碼。",
        ["InputFormat"] = "查詢輸入格式 plain 或 qwen-query。",
        ["QueryInstruction"] = "qwen-query 的檢索任務指令快照。",
        ["ChunkerConfiguration"] = "切段器版本及 token／重疊參數快照；重建期間保留舊版本。",
        ["ActivatedAt"] = "此 profile 完整覆蓋並切換為 active 的 UTC 時間。",
        ["RetiredAt"] = "此 profile 退役的 UTC 時間；作為保留期清理依據。",
        ["ArtifactId"] = "關聯成果文件的識別碼。", ["Version"] = "業務版本號，用於歷史或樂觀並行控制。",
        ["SourceMessageId"] = "此成果版本所引用的來源訊息識別碼。", ["SourceId"] = "外部資料來源識別碼。",
        ["ExternalId"] = "外部來源中的紀錄識別碼。", ["Revision"] = "外部來源或 repository 的固定版本識別。",
        ["ImportedAt"] = "此來源版本明確匯入的時間。", ["ShareId"] = "關聯分享的識別碼。",
        ["SnapshotJson"] = "分享時的固定內容快照；不隨後續編輯變動。", ["IncludeAttachments"] = "是否明確允許分享附件。",
        ["ExpiresAt"] = "分享或授權到期時間。", ["GrantedAt"] = "角色或資源授權建立時間。",
        ["Rating"] = "使用者對回答的評分。", ["Reason"] = "回饋或操作理由。", ["Note"] = "使用者提供的補充說明。",
        ["SetId"] = "評測題庫識別碼。", ["SetTitle"] = "評測執行當時的題庫名稱快照。", ["SetVersion"] = "評測執行當時的題庫版本。",
        ["CasesJson"] = "固定評測案例的 JSON 快照。", ["VariantsJson"] = "評測模型／參數組合的 JSON 快照。",
        ["JobId"] = "關聯背景工作識別碼。", ["CaseIndex"] = "評測案例的從零開始索引。", ["VariantIndex"] = "評測模型／參數組合的從零開始索引。",
        ["Output"] = "評測模型的實際回答。", ["Truncated"] = "評測輸出是否因上限截斷。",
        ["RequiredMatches"] = "命中的必要條件數。", ["RequiredTotal"] = "必要條件總數。", ["ForbiddenMatches"] = "命中的禁止條件數。",
        ["NeedsReview"] = "此評測結果是否需要人工覆核。", ["ReviewScore"] = "人工覆核分數；未覆核保持空值。", ["ReviewNote"] = "人工覆核意見。",
        ["BaseUrl"] = "Gitea 連線主機位址。", ["Login"] = "外部服務的使用者登入名稱。",
        ["ProtectedToken"] = "以 ASP.NET Data Protection 保護的外部 token；不可在 API、稽核或日誌回傳。",
        ["ConnectedAt"] = "使用者建立外部服務連線的時間。", ["Repository"] = "Gitea repository 的 owner/name 識別。",
        ["TextContent"] = "純文字來源的可編輯內容；一般上傳原檔保持空值。",
        ["TextVersion"] = "純文字內容的樂觀並行版本號。",
        ["EventKey"] = "通知來源事件的冪等識別碼。",
        ["Severity"] = "通知呈現層級：info、success 或 error。",
        ["Body"] = "通知摘要，不包含完整私密原文。",
        ["TargetKind"] = "已核准的功能導向類型。",
        ["TargetId"] = "通知所指向的業務識別碼。",
        ["ReadAt"] = "通知已閱讀的時間；空值代表未讀。",
        ["DismissedAt"] = "通知移除的時間；空值代表仍可查看。",
        ["BaseCommit"] = "區間 review 的起點 commit SHA；空值表示單一 commit。",
        ["ConfigurationFingerprint"] = "固定模型與生成設定的 SHA-256 指紋。",
        ["ReviewId"] = "關聯私人程式碼 review 的識別碼。",
        ["Commit"] = "匯入當時固定的 commit SHA。", ["Path"] = "repository 內的檔案路徑，不是伺服器路徑。",
    };

    public static void Configure(ModelBuilder model)
    {
        foreach (var entity in model.Model.GetEntityTypes())
        {
            var table = entity.GetTableName() ?? throw new InvalidOperationException("Every entity must map to a documented table.");
            if (!Tables.TryGetValue(table, out var purpose)) throw new InvalidOperationException($"Missing table description: {table}");
            entity.SetComment(purpose);
            foreach (var property in entity.GetProperties())
            {
                if (!Columns.TryGetValue(property.Name, out var description)) throw new InvalidOperationException($"Missing column description: {table}.{property.Name}");
                property.SetComment(description);
            }
        }
    }
}
